---
- name: Setup Windows Server
  hosts: IIS
  tasks:
    - name: Rename the server
      win_hostname:
        name: PS-IIS01
      register: rename_result

    - block:
        - name: Reboot the server if necessary
          win_reboot:
            msg: "Rebooting the server after renaming"
            pre_reboot_delay: 0
            post_reboot_delay: 120  # Wait for 2 minutes (120 seconds) after reboot
      when: rename_result.reboot_required

    - name: Install IIS
      win_feature:
        name: Web-Server
        state: present

    - name: Install ASP.NET
      win_feature:
        name: Web-Asp-Net45
        state: present

    - name: Install IIS Management Tools
      win_feature:
        name: Web-Mgmt-Tools
        state: present

    - name: Install Chocolatey
      win_chocolatey:
        name: chocolatey
        state: present

    - name: Delete Default IIS Site
      ansible.windows.win_powershell:
        script: |
          Start-Process powershell -ArgumentList "Remove-WebSite -Name 'Default Web Site'" -Verb RunAs

    - name: Install Git
      win_chocolatey:
        name: git
        state: present

    - name: Clone MySampleIIS repository
      win_command: git clone https://github.com/tankokkeng/MySampleIIS.git C:\inetpub\wwwroot\MySampleIIS
      args:
        creates: C:\inetpub\wwwroot\MySampleIIS

    - name: Create MySampleIIS site
      ansible.windows.win_powershell:
        script: |
          Import-Module WebAdministration
          New-Website -Name "MySampleIIS" -Port 80 -PhysicalPath "C:\inetpub\wwwroot\MySampleIIS" -ApplicationPool "DefaultAppPool"
