---
- name: Configure Windows hostname, install IIS and IIS Management Console, and reboot if required
  hosts: IIS
  gather_facts: no

  tasks:
    - name: Set the hostname to "PG-IIS"
      ansible.windows.win_hostname:
        name: PG-IIS
      register: hostname_result

    - name: Display result of hostname change
      debug:
        var: hostname_result

    - name: Install IIS and IIS Management Console
      ansible.windows.win_feature:
        name:
          - Web-Server           # IIS
          - Web-Mgmt-Console     # IIS Management Console
        state: present
      register: iis_install_result

    - name: Display result of IIS and IIS Management Console installation
      debug:
        var: iis_install_result

    - name: Reboot if required by installation
      ansible.windows.win_reboot:
      when: iis_install_result.reboot_required
      register: reboot_result

    - name: Wait for system to come back after reboot
      ansible.windows.win_wait_for:
        port: 5986  # Default WinRM port, adjust if needed
        timeout: 300
      when: iis_install_result.reboot_required
