---
- name: Configure Windows hostname and install IIS
  hosts: IIS  # Define your target hosts here
  gather_facts: no  # Optional for Windows setups

  tasks:
    - name: Set the hostname to "PG-IIS"
      ansible.windows.win_hostname:
        name: PG-IIS
      register: hostname_result

    - name: Display result of hostname change
      debug:
        var: hostname_result

    - name: Install IIS
      ansible.windows.win_feature:
        name: Web-Server
        state: present
      register: iis_install_result

    - name: Display result of IIS installation
      debug:
        var: iis_install_result
