---
- name: Configure Windows hostname, install IIS, disable IPv6, install Chocolatey and Git, and set up IIS site with code from GitHub
  hosts: IIS
  gather_facts: no

  tasks:
    - name: Set the hostname to "PG-IIS"
      ansible.windows.win_hostname:
        name: PG-IIS
      register: hostname_result

    - name: Display result of hostname change
      debug:
        var: hostname_result

    - name: Install IIS and IIS Management Console
      ansible.windows.win_feature:
        name:
          - Web-Server           # IIS
          - Web-Mgmt-Console     # IIS Management Console
        state: present
      register: iis_install_result

    - name: Display result of IIS and IIS Management Console installation
      debug:
        var: iis_install_result

    - name: Disable IPv6 on the NIC
      ansible.windows.win_regedit:
        path: HKLM\SYSTEM\CurrentControlSet\Services\Tcpip6\Parameters
        name: DisabledComponents
        type: dword
        value: 0xFFFFFFFF  # Disables all IPv6 components
      register: disable_ipv6_result

    - name: Display result of IPv6 disable task
      debug:
        var: disable_ipv6_result

    - name: Reboot if required by IIS installation or IPv6 setting
      ansible.windows.win_reboot:
      when: iis_install_result.reboot_required or disable_ipv6_result.reboot_required
      register: reboot_result

    - name: Wait for system to come back after reboot
      ansible.windows.win_wait_for:
        port: 5986  # Default WinRM port, adjust if needed
        timeout: 300
      when: iis_install_result.reboot_required or disable_ipv6_result.reboot_required

    - name: Install Git using Chocolatey
      win_chocolatey:
        name: git
        state: present
      register: git_install_result
      when: "'Chocolatey v' in chocolatey_install_result.stdout"  # Ensure Chocolatey is installed

    - name: Display result of Git installation
      debug:
        var: git_install_result

    - name: Clone IIS website code from GitHub if not already present
      ansible.windows.win_command: |
        git clone https://github.com/AzureWorkshops/samples-simple-iis-website C:\inetpub\wwwroot\samples-simple-iis-website
      args:
        chdir: C:\inetpub\wwwroot
      register: git_clone_result
      ignore_errors: yes  # Ignore errors if repo already exists

    - name: Update IIS website code if already cloned
      ansible.windows.win_command: |
        git pull
      args:
        chdir: C:\inetpub\wwwroot\samples-simple-iis-website
      when: git_clone_result.failed  # Only run if the clone command failed (repo already exists)
      register: git_pull_result

    - name: Configure IIS site for the cloned website
      community.windows.win_iis_website:
        name: "SampleIISWebsite"
        physical_path: "C:\\inetpub\\wwwroot\\samples-simple-iis-website"
        state: started
        port: 80
      register: iis_site_result

    - name: Display result of IIS site configuration
      debug:
        var: iis_site_result
